export const GeneralTopics = {
    Geography: "Geography",
    History: "History",
    Music: "Music",
    Sports: "Sports",
    GeneralKnowledge: "General knowledge",
    Film: "Film",
    Literature: "Literature",
    Mathematics: "Mathematics",
    Religion: "Religion",
    DisneyTriviaQuestions: "Disney trivia questions",
    PopularCulture: "Popular culture",
    DisneyTrivia: "Disney Trivia",
    Art: "Art",
    ChristmasTrivia: "Christmas trivia",
    Education: "Education",
    BakingTrivia: "Baking trivia",
    CasinoTrivia: "Casino trivia",
    Infant: "Infant",
    ComedyTrivia: "Comedy trivia",
    ClassicRockTrivia: "Classic rock trivia",
    Biology: "Biology",
    Astronomy: "Astronomy",
    BatmanTrivia: "Batman trivia",
    Trivia1980s: "1980s trivia"
}